### ISSUE TITLE
Cannot configure macvlan correctly on Raspberry Pi 3b

### ISSUE THREAD

**Issue by RemakingEden** [chriscrowe/docker-pihole-unbound#1]
Hi Chris,

Thanks for putting this all together, this is not so much an issue as it is my inability to set this up correctly. In my network 192.168.1.5 to 192.168.1.10 is taken. So I tried to configure the macvlan to use 192.168.11 and 192.168.1.12. This was my docker-compose file.

```

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      # - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
    environment:
      ServerIP: 192.168.1.11
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: 192.168.1.12
      DNS2: 192.168.1.13
    volumes:
      - /var/lib/docker/pihole-unbound/pihole/volume:/etc/pihole:rw
      - /var/lib/docker/pihole-unbound/pihole/config/hosts:/etc/hosts:ro
      - /var/lib/docker/pihole-unbound/pihole/config/resolv.conf:/etc/resolv.conf:ro
      - /var/lib/docker/pihole-unbound/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - /var/lib/docker/pihole-unbound/pihole/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 192.168.1.11
 restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02

      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: 192.168.1.12
      DNS2: 192.168.1.13
    volumes:
      - /var/lib/docker/pihole-unbound/pihole/volume:/etc/pihole:rw
      - /var/lib/docker/pihole-unbound/pihole/config/hosts:/etc/hosts:ro
      - /var/lib/docker/pihole-unbound/pihole/config/resolv.conf:/etc/resolv.conf:ro
      - /var/lib/docker/pihole-unbound/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - /var/lib/docker/pihole-unbound/pihole/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 192.168.1.11
    restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    ports:
      - 53/tcp
      - 53/udp
    networks:
      home:
        ipv4_address: 192.168.1.12
    restart: always

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.11/30 # 192.168.1.5 and 192.168.1.6
```
 My status shows as 
```
CONTAINER ID        IMAGE                   COMMAND             CREATED             STATUS                             PORTS               NAMES
203d7135189c        pihole/pihole:latest    "/s6-init"          9 minutes ago       Up 41 seconds (health: starting)                       pihole
c0557b4f3e8e        mvance/unbound:latest   "/unbound.sh"       9 minutes ago       Restarting (1) 4 seconds ago                           unbound
```
A scan shows 192.168.1.11 as active but not 192.168.1.12

My logs for "Unbound" show
```
standard_init_linux.go:211: exec user process caused "exec format error"
```
I have read through the linked macvlan documentation but I cannot figure it out. Do you have any suggestions please? Is this to do with running on arm software?

Thanks
