### ISSUE TITLE
Does not respect certain environment settings

### ISSUE THREAD

**Issue by istvnurbn** [chriscrowe/docker-pihole-unbound#172]
Hi All,

I found that pihole-unbound does not respect the `QUERY_LOGGING` and all the `REV_SERVER*` environment settings.

I have not exposed the web port because I use multiple we services on that machine and they are handled by nginx (same internal docker network).

I do not know whether is it a configuration issue on my end or some kind of a weird behavior.

I have the following config for reference:

```YML
version: "3"
services:

  pihole:
    image: 'cbcrowe/pihole-unbound:latest'
    container_name: pihole
    hostname: pihole
    domainname: pihole.local
    restart: unless-stopped

    environment:
      - QUERY_LOGGING="false"
      - DNSSEC="true"
      - DNSMASQ_LISTENING=all
      - DNS_BOGUS_PRIV="true"
      - DNS_FQDN_REQUIRED="true"
      - FTLCONF_LOCAL_IPV4=10.0.0.10
      - TZ=Europe/Budapest
      - WEBPASSWORD=XXXXXX
      - REV_SERVER="true"
      - REV_SERVER_DOMAIN=local
      - REV_SERVER_TARGET=10.0.0.1
      - REV_SERVER_CIDR=10.0.0.0/24
      - HOSTNAME=nas
      - DOMAIN_NAME=pihole.local
      - PIHOLE_WEBPORT=80
      - WEBTHEME=default-light
      - PIHOLE_DNS_=127.0.0.1#5335
    volumes:
      - YYYYYY/appdata/pihole/:/etc/pihole:rw
      - YYYYYY/pihole-dnsmasq/:/etc/dnsmasq.d:rw
    ports:
      - '53:53/tcp'
      - '53:53/udp'

networks:
  default:
    name: nas
```
