### ISSUE TITLE
Issues with spinning up container 

### ISSUE THREAD

**Issue by louis-manabat** [chriscrowe/docker-pihole-unbound#235]
Hi hi,
I'm working on trying to spin up a dedicated Pi-hole server on a separate RPi4 I have, which is running Raspberry Pi OS. 

I am able to spin up the container with no issues, but after going through the logs on Portainer, I get the following error `([✗] DNS resolution is currently unavailable)`. This error also appears if I try to update gravity via Pi-hole's UI. I ran the exact docker-compose config on my other RPi4 and it wasn't giving me these errors. 

Another issue I am having is that I'm trying to set-up bind mounts as well for gravity-sync (snippet below) - I get the following error when trying to compare servers `Hashing the remote Gravity Databasemd5sum: ~/.pihole/pihole/gravity.db: No such file or directory`

```
volumes:
          - type: bind
            source: ~/.pihole/pihole
            target: /etc/pihole:rw
          - type: bind
            source: ~/.pihole/dnsmasq.d
            target: /etc/dnsmasq.d:rw
```

Any help would be greatly appreciated! Thanks
