### ISSUE TITLE
DoH/DoT Support

### ISSUE THREAD

**Issue by newsera** [chriscrowe/docker-pihole-unbound#57]
Are there any plans to support DNS over HTTPs or DNS over TLS? 
Also curious to know, if the DNS traffic towards the root servers are encrypted from the pihole instance?

**Comment by newsera** [comment]
I tried adding the following to unbound.conf file, but didn't help

```

    server:
        tls-cert-bundle: /etc/ssl/certs/ca-certificates.crt

    forward-zone:
        # Forward all queries (except those in cache and local zone) to
        # upstream recursive servers
        name: "."

        # Queries to this forward zone use TLS
        forward-tls-upstream: yes

        # https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers

        # Cloudflare
        forward-addr: 1.1.1.1@853#cloudflare-dns.com
        forward-addr: 1.0.0.1@853#cloudflare-dns.com

```
