### ISSUE TITLE
Use macvlan with the one-container method?

### ISSUE THREAD

**Issue by LeonardoMantovani** [chriscrowe/docker-pihole-unbound#59]
I followed your guide to set up pi-hole and unbound in docker using only one container and everything worked fine (thanks!)

Now I would like to repeat the procedure on another computer that is already running Nextcloud on port 80
So I read that, theoretically, I could use *macvlan* to assign a static IP address to my containers, avoiding conflicts with the host's port 80... Is it possible also while using your `docker-compose`? And if so what should be changed in the `.yaml` file to do it?

**Comment by si458** [comment]
@LeonardoMantovani this is my docker-compose i use with `macvlan`, it works a treat!
just remember to create your macvlan FIRST! i created one called `macvlan101` so i knew the macvlan used my 101 vlan
```
version: '2'
services:
  pihole:
    image: cbcrowe/pihole-unbound:latest
    environment:
      - ADMIN_EMAIL=me@email.com
      - TZ=Europe/London
      - WEBPASSWORD=mypassword
      - ServerIP=192.168.52.10
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC=true
    volumes:
      - data:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      macvlan101:
        ipv4_address: 192.168.52.10
volumes:
  data:
  dnsmasq:
networks:
  macvlan101:
    external:
      name: macvlan101
```
