### ISSUE TITLE
not accessible from synology itself

### ISSUE THREAD

**Issue by bruvv** [chriscrowe/docker-pihole-unbound#6]
When I run your setup synology itself cannot ping to the docker container (destination host unreachable) and thus when using openvpn in the synology package it cannot find the DNS server. To overcome this I have made an extra network in bridge mode and use that ip in my openvpn DNS and synology dns ;) 
as an example:
```
version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      #- 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
    environment:
      ServerIP: 192.168.2.91
      WEBPASSWORD: politie
      DNS1: 192.168.2.92
      DNS2: 192.168.2.254
      DNSMASQ_LISTENING: local
    volumes:
      - /volume1/docker/pihole-unbound/pihole/volume:/etc/pihole:rw
      - /volume1/docker/pihole-unbound/pihole/config/hosts:/etc/hosts:ro
      - /volume1/docker/pihole-unbound/pihole/config/resolv.conf:/etc/resolv.conf:ro
      - /volume1/docker/pihole-unbound/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - /volume1/docker/pihole-unbound/pihole/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 192.168.2.91
    restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    ports:
      - 53/tcp
      - 53/udp
    networks:
      home:
        ipv4_address: 192.168.2.92
    restart: always

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
          ip_range: 192.168.2.91/31 # 192.168.1.5 and 192.168.1.6

networks:
  home:
    driver: bridge
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.3.0/24
          gateway: 192.168.3.254
          ip_range: 192.168.3.10/31 # 192.168.1.5 and 192.168.1.6

```
